/** @type {import('prettier').Config} */
module.exports = {
  semi: false,
  plugins: ["@ianvs/prettier-plugin-sort-imports"],
  importOrder: [
    "^(react/(.*)$)|^(react$)",
    "^(next/(.*)$)|^(next$)",
    "<THIRD_PARTY_MODULES>",
    "",
    "^types$",
    "^@/src/types/(.*)$",
    "^@/src/config/(.*)$",
    "^@/src/lib/(.*)$",
    "^@/src/hooks/(.*)$",
    "^@/src/components/ui/(.*)$",
    "^@/src/components/(.*)$",
    "^@/src/registry/(.*)$",
    "^@/src/styles/(.*)$",
    "^@/src/app/(.*)$",
    "",
    "^[./]",
  ],
  importOrderParserPlugins: ["typescript", "jsx", "decorators-legacy"],
  importOrderTypeScriptVersion: "5.0.0",
}
